name: portfolio

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy_menu_app_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to actions runner
        uses: actions/checkout@v4
      - name: Setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build
      - name: Deploy files to server
        run: |
          SSHOST=${{ vars.SERVER_IP }}
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cd ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sshkey.rsa
          chmod 600 sshkey.rsa
          rsync -rlgoDzvc -i --delete --exclude={'.git*'} --rsh "ssh -p 22 -i ~/.ssh/sshkey.rsa -o StrictHostKeyChecking=no" $GITHUB_WORKSPACE/dist/portfolio/ root@${SSHOST}:/home/portfolio
          ssh -i ~/.ssh/sshkey.rsa -o StrictHostKeyChecking=no root@${SSHOST} "sudo systemctl restart nginx"